### ISSUE TITLE
Uppercase being converted to lower case

### ISSUE THREAD

**Issue by peteringram0** [chenka/html2jade.org#23]
This is an issue when you are using Vue for components, must also be an issue for react (which need to be uppercase)

Input:
````html
<Layout>
	<Slider></Slider>
</Layout>
````

Output:
````jade
layout
	slider
````

Expected Output:
````jade
Layout
	Slider
````

**Comment by prowave** [comment]
This also breaks any Angular conversions.  i.e. `ngModel` becomes `ngmodel`, which is not the same thing.

**Comment by peteringram0** [comment]
@antfu would you accept a pull request for this?

**Comment by antfu** [comment]
@peteringram0 I would love to. But after a quick going through the code, this converter relays on the browser's parser engine, which I case-insensitive. So in order to fix this issue, we should replace the parser. It's a bit complicated. I'm sorry I don't have much time to do this right now and it's better if the owner would happy to do that.

**Comment by ly10121024** [comment]
That's too bad
